{
    "uid": "d1156b3bf0c7b29691657ec93e54440cce552209a22a9cd3a42f9cb1b5c61370",
    "topic": "Python",
    "version": "3.7",
    "jqrs": [
        "3.2.6"
    ],
    "ksas": [
        79
    ],
    "workrole": [
        "Basic Dev"
    ],
    "proficiency": "A",
    "complexity": 1,
    "etc": 2.25,
    "creation_date": "2019-08-20 16:09:58",
    "revision_date": "2020-01-30 15:56:42",
    "revision_number": 1,
    "disabled": false,
    "provisioned": 0,
    "passes": 0,
    "attempts": 0,
    "failures": 0,
    "knowledge": {
        "question": "Which of the following is NOT a keyword used in Python exception handling?",
        "snippet": null,
        "choices": [
            "finally",
            "break",
            "try",
            "except"
        ],
        "answer": 1,
        "explanation": [
            "Try, except, and finally are all exception handling keywords; break is not an exception handling keyword but does allow breaking out of loops."
        ]
    }
}